version: '3'

services:
  account-app:
    build: env-local/account-app
    environment:
      - APP_ENV=local
      - TZ=Asia/Tokyo
      - NPM_PULL_TOKEN=$NPM_PULL_TOKEN
    volumes:
      - ./packages/account:/app/account
      - ./packages/site_config:/app/site_config
      - ./packages/shared:/app/shared
      - /app/account/node_modules
      - /app/account/.next
      - ~/.npmrc:/.npmrc
    networks:
      - h2umono
  helloero-app:
    build: env-local/helloero-app
    environment:
      - APP_ENV=local
      - TZ=Asia/Tokyo
      - NPM_PULL_TOKEN=$NPM_PULL_TOKEN
    volumes:
      - ./packages/helloero:/app/helloero
      - ./packages/site_config:/app/site_config
      - ./packages/shared:/app/shared
      - /app/helloero/node_modules
      - /app/helloero/.next
      - ~/.npmrc:/.npmrc
    networks:
      - h2umono
  help-app:
    build: env-local/help-app
    environment:
      - APP_ENV=local
      - TZ=Asia/Tokyo
      - NPM_PULL_TOKEN=$NPM_PULL_TOKEN
    volumes:
      - ./packages/help:/app/help
      - ./packages/site_config:/app/site_config
      - ./packages/shared:/app/shared
      - /app/help/node_modules
      - /app/help/.next
      - ~/.npmrc:/.npmrc
    networks:
      - h2umono
  h2umono-nginx:
    image: nginx
    networks:
      - h2umono
    ports:
      # Docker for mac unable to compose ip based connection
      # https://docs.docker.com/docker-for-mac/networking/#i-cannot-ping-my-containers
      - '80:80'
      - '443:443'
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./env-local/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./env-local/nginx/config/conf.d:/etc/nginx/conf.d:ro
      - ./env-local/nginx/config/tls:/etc/nginx/tls:ro
    depends_on:
      - account-app
      - helloero-app
      - help-app
networks:
  h2umono:
