version: '3'

services:
  account-app:
    build: env-local/account-app
    environment:
      - APP_ENV=local
      - TZ=Asia/Tokyo
      - NPM_PULL_TOKEN=$NPM_PULL_TOKEN
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - .npmrc:/app/.npmrc
      - ./packages/account:/app/packages/account
      - ./packages/shared:/app/packages/shared
      - ./packages/site_config:/app/packages/site_config
      - ./packages/types:/app/packages/types
      - /app/node_modules
      - /app/packages/account/.next
    networks:
      - h2umono
  helloero-app:
    build: env-local/helloero-app
    environment:
      - APP_ENV=local
      - TZ=Asia/Tokyo
      - NPM_PULL_TOKEN=$NPM_PULL_TOKEN
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - .npmrc:/app/.npmrc
      - ./packages/helloero:/app/packages/helloero
      - ./packages/shared:/app/packages/shared
      - ./packages/site_config:/app/packages/site_config
      - ./packages/types:/app/packages/types
      - /app/node_modules
      - /app/packages/helloero/.next
    networks:
      - h2umono
  help-app:
    build: env-local/help-app
    environment:
      - APP_ENV=local
      - TZ=Asia/Tokyo
      - NPM_PULL_TOKEN=$NPM_PULL_TOKEN
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - .npmrc:/app/.npmrc
      - ./packages/help:/app/packages/help
      - ./packages/shared:/app/packages/shared
      - ./packages/site_config:/app/packages/site_config
      - ./packages/types:/app/packages/types
      - /app/node_modules
      - /app/packages/help/.next
    networks:
      - h2umono
  h2umono-nginx:
    image: nginx
    networks:
      - h2umono
    ports:
      # Docker for mac unable to compose ip based connection
      # https://docs.docker.com/docker-for-mac/networking/#i-cannot-ping-my-containers
      - '80:80'
      - '443:443'
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./env-local/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./env-local/nginx/config/conf.d:/etc/nginx/conf.d:ro
      - ./env-local/nginx/config/tls:/etc/nginx/tls:ro
    depends_on:
      - account-app
      - helloero-app
      - help-app
networks:
  h2umono:
