export const i18n_messages = {
  attention: '注意',
  dub: '吹',
  keyboardShortcut: 'キーボードショートカット',
  'live.kana': 'ライブ配信',
  'mediaOverlay.backToViewer': '最後のページに戻る',
  'mediaOverlay.replay': 'もう一度観る',
  'music.kana': 'ミュージック',
  'playcard.video.isplayingcamera': '視聴中',
  'player.cameras': 'カメラ切替',
  'player.episodes': 'エピソード',
  'player.setting': '設定',
  'setting.bitrate': '画質',
  'setting.bitrateAuto': '自動',
  'setting.bitrateHigh': '高画質',
  'setting.bitrateLow': '低画質',
  'setting.dub': '吹替',
  'setting.playbackRate': '再生速度',
  'setting.sub': '字幕',
  'setting.subDub': '字幕・吹替',
  'shortcut.common.cancelFullscreen': 'フルスクリーンを解除',
  'shortcut.common.fullscreen': 'フルスクリーンの切り替え',
  'shortcut.common.showShortcut': 'ショートカットを表示',
  'shortcut.video.decreasePlayRate': '再生速度を減少',
  'shortcut.video.forward10': '10秒進む',
  'shortcut.video.forward30': '30秒進む',
  'shortcut.video.increasePlayRate': '再生速度を増加',
  'shortcut.video.lowerVolume': '音量を下げる',
  'shortcut.video.mute': '音量をミュート',
  'shortcut.video.pictureInPicture': 'ミニプレイヤーで再生',
  'shortcut.video.playPause': '再生 / 一時停止の切り替え',
  'shortcut.video.raiseVolume': '音量を上げる',
  'shortcut.video.rewind10': '10秒戻る',
  'shortcut.video.rewind30': '30秒戻る',
  sub: '字',
  subdub: '字・吹',
  'video.kana': 'ビデオ',
} as const;
